extends:
  - eslint:recommended
  - plugin:prettier/recommended

env:
  browser: true
  es6: true

globals:
  Rails: readonly

parser: "@babel/eslint-parser"

rules:
  curly:
    - error
    - multi-line
  no-console: error
  no-template-curly-in-string: error
  no-var: error
