extends:
  - stylelint-config-standard
  - stylelint-config-sass-guidelines
  - stylelint-prettier/recommended

rules:
  function-no-unknown:
    - true
    - ignoreFunctions:
      - lighten
      - darken
      - string.unquote
