extends:
  - stylelint-config-standard
  - stylelint-config-sass-guidelines
  - stylelint-prettier/recommended

plugins:
  - stylelint-scss

rules:
  function-no-unknown:
    - true
    - ignoreFunctions:
      - lighten
      - darken
      - string.unquote
  scss/no-global-function-names:
    - null
